FROM ruby:3.3.8-slim

WORKDIR /app

RUN apt-get update -qq && apt-get install -y --no-install-recommends \
  build-essential \
  libmariadb-dev \
  libyaml-dev \
  nodejs \
  yarn \
  curl \
  git \
  && rm -rf /var/lib/apt/lists/*

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

CMD ["bundle", "exec", "foreman", "start", "-f", "Procfile.dev"]