apiVersion: v1
kind: Service
metadata:
  name: rails-service
spec:
  selector:
    app: rails-app # 対象のPod（ラベル）を指定
  ports:
    - protocol: TCP
      port: 80 # 外部からアクセスするポート（サービス側）
      targetPort: 3000 # コンテナ内のポート（アプリがリッスン)
